[project]
name = "mela"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "ebooklib>=0.18",
    "html2text>=2024.2.26",
    "markitdown[all]>=0.1.3",
    "openai>=1.66.3",
    "pillow>=11.1.0",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "ruff>=0.11.6",
]
